language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

services:
  - memcached

before_script:
  - "make vendor"
  - "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then phpenv config-add .travis.php.ini; fi"
  - "make travis-env"

script: make

cache:
  directories:
    - vendor

notifications:
  email: false
