language: php
php:
  - 5.5
  - 5.4
before_script:
  - git submodule update --init
  - pyrus channel-discover pear.phpunit.de
  - pyrus channel-discover pear.netpirates.net
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - pyrus install phpunit/phpcpd
  - phpenv rehash
script: ant test-travis
