base_url = "https://www.mcdermottroe.com"
build_search_index = false
compile_sass = true
feed_filenames = [ "rss.xml" ]
generate_feeds = true
theme = "anatole-zola"
title = "Conor McDermottroe"

taxonomies = [
  { name = "tags", paginate_by = 10 },
]

[translations]
about = "About"
home = "Home"
cv = "CV/Resume"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Previous Page"
date_format = "%Y-%m-%d"

[markdown.highlighting]
theme = "github-light"

[extra.show]
tags = true

[extra.social]
github = "conormcd"
instagram = "irlconor"
linkedin = "conormcdermottroe"
mastodon = "https://mastodon.social/@irlconor"
