---

version: "2.1"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context:
            - fastmail-ftp
          filters:
            branches:
              only:
                - master

jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Fetch and install Zola
          command: |
            curl -Lso zola.tar.gz https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz
            tar xzf zola.tar.gz
            sudo mv zola /usr/bin/zola
      - run:
          name: Check all links
          command: zola check || true
      - run:
          name: Build the site
          command: zola build
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    docker:
      - image: rclone/rclone:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: rclone config
          command: |
            mkdir -p ~/.config/rclone
            cat > ~/.config/rclone/rclone.conf \<<EOF
            [fastmail]
            type = webdav
            url = https://myfiles.fastmail.com
            vendor = other
            user = conor@mcdermottroe.com
            EOF
      - run:
          name: rclone sync
          command: |
            export RCLONE_WEBDAV_PASS=$(echo "${WEBDAV_PASS}" | rclone obscure -)
            rclone sync public fastmail:www.mcdermottroe.com
